In [1]:
from src.params import PROCESSED

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import glob
import time
import os
from os.path import join
from scipy.stats import zscore
import pickle


## Transformations
def convert_folders():
    return


data_df = pd.read_csv(join(PROCESSED,"fc.tsv"),sep="\t", index_col=0)
data_df

Project Directory: /data2/isshamie/time_neutrophils

Config paths:
__name__ src.params
__package__ src
__file__ /data2/isshamie/time_neutrophils/src/params.py
__cached__ /data2/isshamie/time_neutrophils/src/__pycache__/params.cpython-37.pyc
path /data2/isshamie/time_neutrophils/src/params.py
DATA_DIR /data2/isshamie/time_neutrophils/data
PROCESSED /data2/isshamie/time_neutrophils/data/processed
PARAM_DIR /data2/isshamie/time_neutrophils/parameters
RESULTS /data2/isshamie/time_neutrophils/results
FIGURES_DIR /data2/isshamie/time_neutrophils/figures

,Timepoint,Stimuli,Sample,Cell Size,Cell Circularity,Cell Aspect Ratio,Cell Tracker Intensity,PI Intensity,AnexinV Intensity
0_2G3,3,G,2,11750,113.2539,2.8375,21192.0999,2951.6684,10590.6212
1_2G3,3,G,2,61,512.9727,61.0000,17836.5246,2907.2951,8491.5246
2_2G3,3,G,2,12,2565.8500,12.0000,18353.1667,2925.5833,8690.5833
3_2G3,3,G,2,23,1351.6133,23.0000,19101.6087,2961.4783,8673.8261
4_2G3,3,G,2,2,10000.0000,2.0000,19001.0000,2935.5000,8735.5000
...,...,...,...,...,...,...,...,...,...
4592_4B46,46,B,4,216,9413.2491,1.0487,14314.2315,4481.2037,27472.5972
4593_4B46,46,B,4,370,4905.5990,3.0213,12515.4270,6447.3568,29679.3784
4594_4B46,46,B,4,157,8635.1936,1.4828,14121.9427,15047.1401,26821.1465
4595_4B46,46,B,4,19,10000.0000,1.2733,20725.6316,46356.0526,26550.7895
4596_4B46,46,B,4,143,6346.1027,2.5904,12771.9371,4949.9021,25461.1259

In [1]:
import pymc3
import umap
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import glob
import time
import os
from scipy.stats import zscore
import pickle
%matplotlib inline

In [2]:
data_df = pd.read_csv("../fc.tsv",sep="\t", index_col=0)
data_df

,Timepoint,Stimuli,Sample,Cell Size,Cell Circularity,Cell Aspect Ratio,Cell Tracker Intensity,PI Intensity,AnexinV Intensity
0_2G3,3,G,2,11750,113.2539,2.8375,21192.0999,2951.6684,10590.6212
1_2G3,3,G,2,61,512.9727,61.0000,17836.5246,2907.2951,8491.5246
2_2G3,3,G,2,12,2565.8500,12.0000,18353.1667,2925.5833,8690.5833
3_2G3,3,G,2,23,1351.6133,23.0000,19101.6087,2961.4783,8673.8261
4_2G3,3,G,2,2,10000.0000,2.0000,19001.0000,2935.5000,8735.5000
...,...,...,...,...,...,...,...,...,...
4592_4B46,46,B,4,216,9413.2491,1.0487,14314.2315,4481.2037,27472.5972
4593_4B46,46,B,4,370,4905.5990,3.0213,12515.4270,6447.3568,29679.3784
4594_4B46,46,B,4,157,8635.1936,1.4828,14121.9427,15047.1401,26821.1465
4595_4B46,46,B,4,19,10000.0000,1.2733,20725.6316,46356.0526,26550.7895
4596_4B46,46,B,4,143,6346.1027,2.5904,12771.9371,4949.9021,25461.1259

In [3]:
data_df=data_df.drop(["Sample", "Timepoint","Stimuli"],axis=1)

## Log variables

In [4]:
data_df_log = np.log10(data_df)

In [6]:
pickle.dump(data_df_log, open("../data/processed/data_df_log10.p","wb"))

## Z Score all variables

In [7]:
data_df_z = data_df.apply(zscore,axis=0)

In [8]:
pickle.dump(data_df_z, open("../data/processed/data_df_z.p","wb"))

In [8]:
data_df_log_z = data_df_log.apply(zscore,axis=0)

In [10]:
pickle.dump(data_df_log_z, open("../data/processed/data_df_log10_z.p","wb"))